<?php
// $Id: views_like_whereclause.module

/**
* @file
* Custom functions for this site.
*/

/**
 * Implementation of hook_views_api().
 */
function views_like_where_views_api() { // your module name into hook_views_api
  return array(
    'api' => 2,
    // might not need the line below, but in any case, the last arg is the name of your module
    'path' => drupal_get_path('module', 'views_like_whereclause'),
  );
}


<?php
function views_like_whereclause_views_query_alter(&$view, &$query) {
if ($view->name == 'events_list_by_taxonomy_term') {
    $view->query->add_where('advf_filter',"(node.type='%s' OR node_comment_statistics.comment_count >= %d)",'forum',1);
    $view->query->set_group_operator('AND');
  }
}
?>